name: update-project-Access
run-name: update-project-Access ${{ inputs.realmtype }} ${{ inputs.project-names }} ${{ inputs.ad-group-name }}
on: 
  workflow_dispatch:
    inputs:
      project-names:
        description: Project Name as comma seperated
        type: string
        required: true
      realmtype:
        description: select the realm type
        type: choice
        options:
          - liam-test
          - liam-us
          - liam-eu
          - liam-apac
      ad-group-name:
        description: Provide the Ad Group/JDA Delivers ID
        type: string
        default: ""
      project-access:
        description: 'Update Project access'
        type: boolean
        required: false
        default: true
      key-valut-acess:
        description: 'update key-valut acess'
        type: boolean
        required: false
        default: true
      storage-account-acess:
        description: 'update storage account acess'
        type: boolean
        required: false
        default: true
jobs:
  AD_Group_updation:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "${{ github.workspace }}/etoe-sol-cicd-e2e/.github/utils"
    steps:
      - name: Summarize Input Parameters
        run: (echo -ne "**Input parameters:**\n|Parameter|Value|\n|---|---|\n|Workflow Branch|${GITHUB_REF#refs/heads/}|\n" && echo '${{ toJson(inputs) }}' | jq -r 'to_entries[] | "|\(.key)|\(.value)|"') >> ${GITHUB_STEP_SUMMARY}
      - name: Clone cicd-e2e repo
        uses: actions/checkout@v4
        with:
          path: etoe-sol-cicd-e2e
      - name: Install dependencies
        run: |
          pip install -r etoe-sol-cicd-e2e/.github/utils/requirements.txt



      

    
       
       
