name: Custom-Access-Manager

on:
  workflow_dispatch:
    inputs:
      realmtype:
        description: 'Realm type (e.g. dev, prod)'
        type: choice
        options:
          - liam-test
          - liam-us
          - liam-eu
          - liam-apac
      project-name:
        description: 'Project Name'
        type: string
        required: true
      user-id:
        description: 'User or Group Identifier'
        type: string
        required: true
      add:
        description: 'Perform Add Operation'
        type: boolean
        default: false
      status:
        description: 'Perform Status Check'
        type: boolean
        default: false
      remove:
        description: 'Perform Remove Operation'
        type: boolean
        default: false
      blocks:
        description: 'Get Blocked Users/Resources'
        type: boolean
        default: false

jobs:
  custom_access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install -r .github/utils/requirements.txt

      - name: Add Access
        if: ${{ inputs.add }}
        run: |
          python .github/utils/add.py ${{ inputs.realmtype }} ${{ inputs.project-name }} ${{ inputs.user-id }}

      - name: Check Status
        if: ${{ inputs.status }}
        run: |
          python .github/utils/status.py ${{ inputs.realmtype }} ${{ inputs.project-name }} ${{ inputs.user-id }}

      - name: Remove Access
        if: ${{ inputs.remove }}
        run: |
          python .github/utils/remove.py ${{ inputs.realmtype }} ${{ inputs.project-name }} ${{ inputs.user-id }}


